replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/pollfish-assignment-1-476108/demo-repo/hello-world
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}
